### ISSUE TITLE
iTerm and Sublime Variants

### ISSUE THREAD

**Issue by jbrooksuk** [Pustur/Calamity-syntax#2]
Please? 🙏

**Comment by Pustur** [comment]
**iTerm**
my PR was just approved [here](https://github.com/mbadolato/iTerm2-Color-Schemes#calamity)

**Sublime**
i tried to port the syntax colors earlier today but i'd like to add the colors to the UI as well. So it's a work in progress.

I'll let you know when i finish it.

Thanks for the suggestions!

**Comment by jbrooksuk** [comment]
Awesome, thanks @Pustur!

**Comment by Pustur** [comment]
Hey @jbrooksuk, i hope you're doing great 🙂

I underestimated the work involved in making a complete UI theme, so i decided to publish only the color scheme. It's supposed to be used in combination with the "Adaptive" UI theme.

I submitted [this PR](https://github.com/wbond/package_control_channel/pull/6719) so once it will be approved you'll be able to install the Calamity theme from the sublime text's package manager.

Meanwhile, if you want to try the theme, you can visit the repo [here](https://github.com/Pustur/calamity-sublime).  
If you find any issues, feel free to report them there.

Have a nice day,
Pustur

**Comment by jbrooksuk** [comment]
Amazing thanks @Pustur!

**Comment by jbrooksuk** [comment]
This is great, I look forward to a theme if you want to continue working on it :)

**Comment by Pustur** [comment]
@jbrooksuk For your information, you can now install Calamity using Sublime's package manager 🎉

**Comment by jbrooksuk** [comment]
Whoop! I have some fixes to send too :)
